DOP-5036 Refactor Search-Manifest integration
mongodb/netlify-integrations pull request #10
Opened 2024-09-27 20:33 UTC by anabellabuckvar

2024-10-04 16:57 UTC, branberry requested changes
Hey Anabella! Overall, this is looking great.

2024-10-04 16:57 UTC, branberry commented on search-manifest/src/uploadToAtlas/getProperties.ts
> +const getProperties = async ({
I didn't catch this previously, but I'd prefer to use named exports as opposed to default exports. You can just add `export const` here, and remove the default export at the bottom.

Default exports can be named anything when imported, so it can lead to confusion and bugs

2024-10-04 16:57 UTC, branberry commented on search-manifest/src/uploadToAtlas/searchConnector.ts
> +export const getDocsetsCollection = async () => {
This looks great!! Thank you for doing this

2024-10-04 16:57 UTC, branberry commented on search-manifest/src/uploadToAtlas/searchConnector.ts
> +  const uri = ENV_VARS.ATLAS_SEARCH_URI;
NIT: I think it might be preferable to use the `ENV_VARS.ATLAS_SEARCH_URI` and other env variables directly as opposed to re-assigning them to another variable. It makes it a little bit harder to track

2024-10-04 16:57 UTC, branberry commented on search-manifest/src/uploadToAtlas/searchConnector.ts
> +  if (snootyDb) {
I think `clusterZeroClient` could be more descriptive for this, as this variable doesn't hold the instance of the `snootyDb`.

What you could do instead is cache the Db instance ie `snootyDb = db(dbName)`

2024-10-04 16:57 UTC, branberry commented on search-manifest/src/uploadToAtlas/getProperties.ts
> +      return { ...branchObj };
this can just be `return branchObj`

2024-10-04 16:57 UTC, branberry commented on search-manifest/src/uploadToAtlas/getProperties.ts
> +export const getBranch = (branches: Array<BranchEntry>, branchName: string) => {
This could be simplified to `(branches, branchName) => branches.find(branch => branch === branchName)`

2024-10-04 19:42 UTC, anabellabuckvar commented on search-manifest/biome.json
> +{
No specific need!

2024-10-04 19:44 UTC, anabellabuckvar commented on search-manifest/src/generateManifest/createFacets.ts
> +    if (subFacets) {
actually, `subFacets` should be an array of facets or `null`, thanks for catching this!

2024-10-04 20:29 UTC, anabellabuckvar commented on search-manifest/src/uploadToAtlas/searchConnector.ts
> +  if (snootyDb) {
I renamed it to clusterZeroClient

2024-10-07 14:18 UTC, anabellabuckvar commented on search-manifest/src/generateManifest/createFacets.ts
> +          new Facet(subFacet.category, subFacet.value, subFacet.subFacets ?? [])
Thanks for catching this as well- `this.subFacets` should have been initialized to an empty array, and then we push a new facet onto it on each iteration over the `subFacets` arg that was passed in

2024-10-07 14:25 UTC, anabellabuckvar commented on search-manifest/src/generateManifest/manifest.ts
> +  constructor(url = "", includeInGlobalSearch = false) {
Nothing, it should always be empty upon initialization because the value will be returned from getProperties and then set to the existing manifest later on

2024-10-07 15:09 UTC, branberry commented on search-manifest/src/generateManifest/createFacets.ts
> +          new Facet(subFacet.category, subFacet.value, subFacet.subFacets ?? [])
Gotcha! I was also wondering if it makes sense to create a new `Facet` instance if the `subFacets` array contains `Facet` objects already. I'm thinking about this more too, and I wonder if this is a good use of a class. I know that we use a class for the `Facet` type in Mut, but this could just be an object:

```ts

interface Facet {
 category: string;
 value: string;
 subFacet: Array<Facet>;
}
```

Also, do we use this class right now? If not, we could probably just remove this for now, and add it later when needed

2024-10-07 21:23 UTC, anabellabuckvar commented on search-manifest/src/generateManifest/createFacets.ts
> +          new Facet(subFacet.category, subFacet.value, subFacet.subFacets ?? [])
changed!

2024-10-08 16:50 UTC, branberry approved these changes
LGTM!

2024-10-08 17:05 UTC, merged