Run formatter and linter on codebase
mongodb/netlify-integrations pull request #11
Opened 2024-09-30 14:42 UTC by branberry

## Notes

This incorporates the auto-formatting and linting fixes using our formatter's CLI tool. 

One caveat is that not all linting related errors are automatically resolved, we'll still have them and we'll need to resolve those manually.

2024-09-30 15:19 UTC, rayangler reviewed
Thanks for doing this! Just one comment about some weird tab inconsistency I'm seeing between a couple of the files

2024-09-30 15:19 UTC, rayangler commented on search-manifest/package.json
> +	"name": "netlify-search-integration",
It feels a bit odd to me to have a tab size of 4 (I think?) for some JS/TS/JSON files and 2 for others (like [snooty-cache](https://github.com/mongodb/netlify-integrations/blob/dc26bfd8547b66ed7da4cd0ee81c13372aa75038/snooty-cache/src/index.ts)). Is there a way where we can standardize maybe to 2, since our JS/TS files in other repos are also 2?

Fwiw, I can't tell if GitHub is playing tricks on the indentation here since the files look fine on my VS Code locally, but there's a clear difference on GitHub 🤔

2024-09-30 15:55 UTC, rayangler approved these changes

2024-09-30 19:35 UTC, anabellabuckvar requested changes
LGTM! Just two requests:

1. Could we add the ability to lint and format within each integration?
2. Could you update the readme with info on running the linter and formatter?

2024-10-07 13:18 UTC, branberry commented
Hey @anabellabuckvar ! Sorry, missed this comment. The single `biome.json` will apply the formatting/linting to all projects automatically. 

I'll definitely update the README with info on how to run the linter/formatter👍

2024-10-14 16:32 UTC, merged