DOP-5007: Improve SearchProperty in Netlify Search Manifest Integration
mongodb/netlify-integrations pull request #3
Opened 2024-09-11 20:47 UTC by anabellabuckvar

2024-09-16 15:52 UTC, branberry requested changes
Hey Anabella! Thank you for all of your work on this. I've left some comments, but I really like where this is going overall. The testing you've added is great

2024-09-16 15:52 UTC, branberry commented on search-manifest/src/uploadToAtlas/getProperties.ts
> +export const getBranch = (branches: any, branchName: string) => {
Let's add a concrete type for `branches`

2024-09-16 15:52 UTC, branberry commented on search-manifest/src/uploadToAtlas/getProperties.ts
> +  throw Error(`Current branch ${branchName} not found in repos branches entry`);
I think we can remove the throw here so that we don't need an extra try/catch on line 77. This function can return `Branch | undefined`, and the error can be thrown where the function is called.

2024-09-16 15:52 UTC, branberry commented on search-manifest/src/uploadToAtlas/uploadManifest.ts
> -    // if (document.facets) {
This can be removed

2024-09-16 15:52 UTC, branberry commented on search-manifest/tests/integration/uploadManifest.test.ts
> +    await checkCollection();
I think we'll want to remove the `checkCollection` call in the `beforeEach`. Since we use it in the tests, we don't need to also do that call there. The `beforeEach` is generally used for setup, so we don't want to do `expect` calls in there.

2024-09-16 15:52 UTC, branberry commented on search-manifest/tests/unit/getProperties.test.ts
> +const removeDocuments = async () => {
Since we have this same function in the `uploadManifest.test.ts` file, we should move this function to the `utils` directory

2024-09-16 15:52 UTC, branberry commented on search-manifest/tests/unit/getProperties.test.ts
> +const repoNames = ["docs-compass", "cloud-docs", "docs-app-services"];
Instead of using an array to define these values, I think it would be more clear if we define each value as their own constant (`const DOCS_COMPASS_NAME = 'docs-compass'`) as it makes it clear in the tests which value you are providing for `process.env.REPO_NAME`

2024-09-17 17:01 UTC, seungpark reviewed
thanks for working on the improvement @anabellabuckvar ! since this is additive to the existing <`generate manifest and upload to S3`>, i think we can just have a change (non additive) in search transport server to test and reflect these changes. lmk when there is a ticket for this and we can flesh out the differences

2024-09-18 14:48 UTC, branberry commented on search-manifest/src/uploadToAtlas/uploadManifest.ts
> +    return status;
You'll want the return at the end of the `try` block instead of the `finally` block. If we return there, then we'll always return `status` even if we throw in the catch block. `finally` always runs even if an error is thrown

2024-09-18 16:46 UTC, anabellabuckvar commented on search-manifest/src/uploadToAtlas/uploadManifest.ts
> +    return status;
That was intentional- I would want to return status either way, unless you think there's a reason we shouldn't be doing that?

2024-09-18 19:16 UTC, branberry commented on search-manifest/src/uploadToAtlas/uploadManifest.ts
> +    return status;
Gotcha, in that case then we wouldn't need the `catch` block as that error is never actually propagated in this case

2024-09-18 21:03 UTC, anabellabuckvar commented on search-manifest/src/uploadToAtlas/uploadManifest.ts
> +    return status;
I see. I was going to just change `status.error` to true where we throw errors, and then keep returning `status` in the `finally ` block, but I can also remove the try catch so the error propagates. Which would you prefer?

2024-09-19 19:38 UTC, branberry approved these changes
Looks great, thank you!!

2024-09-19 20:26 UTC, merged