Dop 5018
mongodb/netlify-integrations pull request #6
Opened 2024-09-16 21:51 UTC by anabellabuckvar

2024-09-23 15:15 UTC, branberry requested changes

2024-09-23 19:18 UTC, anabellabuckvar commented on search-manifest/src/index.ts
> +    }: { searchProperty: string; url: string; includeInGlobalSearch: boolean } =
If it's all right, I'll do this as part of [DOP-4830](https://github.com/mongodb/netlify-integrations/pull/7) because it adds another property to the return type anyways

2024-09-23 19:22 UTC, anabellabuckvar commented on search-manifest/tests/integration/uploadManifest.test.ts
> +      await mockDb();
correct

2024-09-23 19:22 UTC, anabellabuckvar commented on search-manifest/src/uploadToAtlas/uploadManifest.ts
> +    await teardown();
Where would you suggest moving it?

2024-09-23 20:13 UTC, branberry commented on search-manifest/src/index.ts
> +    if (processedDoc) manifest.addDocument(processedDoc);
I think we can put the teardown function call at the end of the integration callback function somewhere here. Basically, the end of the `addBuildEventHandler` callback, you can add the teardown there

2024-09-23 20:47 UTC, anabellabuckvar commented on search-manifest/tests/unit/getProperties.test.ts
> +      await expect(getProperties(BRANCH_NAME_MASTER)).rejects.toThrow();
Since it's an async function where the `reject` needs to be captured too, we have to `await`  the expect and leave it there

2024-09-24 15:08 UTC, branberry approved these changes
Hey Anabella! One small nit, but everything else looks good to me. Thank you!

2024-09-24 15:08 UTC, branberry commented on search-manifest/src/generateManifest/manifest.ts
>      if (document) {
`document` is of type `ManifestEntry` meaning that it shouldn't be undefined. We can remove this check here.

2024-09-24 15:45 UTC, anabellabuckvar commented on search-manifest/src/index.ts
> +    if (processedDoc) manifest.addDocument(processedDoc);
Discussed async, postponing to solve in later ticket

2024-09-24 15:49 UTC, merged